# Generated by Django 5.2.4 on 2025-07-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_caixa'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='bandeira_cartao',
            field=models.CharField(blank=True, choices=[('ELO', 'Elo'), ('VISA', 'Visa'), ('MASTERCARD', 'Mastercard'), ('AMEX', 'American Express'), ('OUTRO', 'Outro')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='nome_cliente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venda',
            name='metodo_pagamento',
            field=models.CharField(choices=[('Dinheiro', 'Dinheiro'), ('PIX', 'PIX'), ('Cartao', 'Cartão')], max_length=20),
        ),
    ]
