# Generated by Django 5.2.4 on 2025-07-22 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_venda_bandeira_cartao_venda_nome_cliente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='nome_cliente',
        ),
        migrations.AddField(
            model_name='venda',
            name='codigo_autorizacao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='nsu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
