# Generated by Django 5.2.4 on 2025-07-22 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_venda_nome_cliente_venda_codigo_autorizacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='bandeira_cartao',
            field=models.CharField(blank=True, choices=[('ELO', 'Elo'), ('VISA', 'Visa'), ('MASTERCARD', 'Mastercard'), ('AMEX', 'Amex'), ('OUTRO', 'Outro')], max_length=20, null=True),
        ),
    ]
