# Generated by Django 5.2.4 on 2025-07-22 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_venda_bandeira_cartao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='bandeira_cartao',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='codigo_autorizacao',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='nsu',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='observacoes',
        ),
        migrations.AlterField(
            model_name='venda',
            name='metodo_pagamento',
            field=models.CharField(default='Dinheiro', max_length=20),
        ),
    ]
