# Generated by Django 5.2.4 on 2025-07-23 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_venda_bandeira_cartao_venda_codigo_autorizacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='foto_notinha',
            field=models.TextField(blank=True, null=True),
        ),
    ]
