# Generated by Django 5.2.4 on 2025-07-24 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_registrocomissao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistroComissao',
        ),
    ]
