# Generated by Django 5.2.4 on 2025-07-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_delete_registrocomissao'),
    ]

    operations = [
        migrations.AddField(
            model_name='caixa',
            name='credito_apurado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='caixa',
            name='debito_apurado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='caixa',
            name='dinheiro_apurado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='caixa',
            name='pix_apurado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
