# Generated by Django 5.2.4 on 2025-07-26 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_caixa_credito_apurado_caixa_debito_apurado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixa',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='caixas_operados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RegistroComissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('planos_mensais', models.PositiveIntegerField(default=0)),
                ('planos_anuais', models.PositiveIntegerField(default=0)),
                ('comissao_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comissoes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
