# Generated by Django 5.2.4 on 2025-07-27 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_caixa_responsavel_registrocomissao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistroComissao',
        ),
    ]
