# Generated by Django 5.2.4 on 2025-07-29 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_delete_registrocomissao'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='caixa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas', to='api.caixa'),
        ),
    ]
