# Generated by Django 5.2.4 on 2025-07-31 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_venda_caixa'),
    ]

    operations = [
        migrations.AddField(
            model_name='caixa',
            name='valor_fechamento_sistema',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
