# Generated by Django 5.2.4 on 2025-08-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_caixa_valor_fechamento_sistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='caixa',
            name='observacoes_anexos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
