# Generated by Django 5.2.4 on 2025-08-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_caixa_observacoes_anexos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caixa',
            name='observacoes_anexos',
        ),
        migrations.AddField(
            model_name='caixa',
            name='credito_sistema_ajustado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='caixa',
            name='debito_sistema_ajustado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='caixa',
            name='dinheiro_sistema_ajustado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='caixa',
            name='pix_sistema_ajustado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
