# Generated by Django 5.2.4 on 2025-08-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_caixa_observacoes_anexos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caixa',
            name='anexo_filipeta',
            field=models.ImageField(blank=True, null=True, upload_to='filipetas/'),
        ),
    ]
