# Generated by Django 5.2.4 on 2025-08-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_caixa_anexo_filipeta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caixa',
            name='anexo_filipeta',
        ),
        migrations.AlterField(
            model_name='venda',
            name='foto_notinha',
            field=models.ImageField(blank=True, null=True, upload_to='notinhas/'),
        ),
    ]
