# Generated by Django 5.2.4 on 2025-08-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_caixa_anexo_filipeta_alter_venda_foto_notinha'),
    ]

    operations = [
        migrations.AddField(
            model_name='caixa',
            name='anexo_filipeta',
            field=models.ImageField(blank=True, null=True, upload_to='filipetas/'),
        ),
    ]
