# Generated by Django 5.2.4 on 2025-08-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_caixa_anexo_filipeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='tipo_cartao',
            field=models.CharField(blank=True, choices=[('Debito', 'Débito'), ('Credito', 'Crédito')], max_length=10, null=True),
        ),
    ]
