# Generated by Django 5.2.4 on 2025-08-04 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_venda_tipo_cartao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caixa',
            name='anexo_filipeta',
        ),
        migrations.AddField(
            model_name='caixa',
            name='evo_credito_apurado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='caixa',
            name='evo_debito_apurado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='caixa',
            name='evo_dinheiro_apurado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='caixa',
            name='evo_pix_apurado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='caixa',
            name='evo_total_apurado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='AnexoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.ImageField(upload_to='anexos_caixa/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('caixa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='api.caixa')),
            ],
        ),
    ]
