# Generated by Django 5.2.4 on 2025-08-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_caixa_anexo_filipeta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caixa',
            name='evo_credito_apurado',
        ),
        migrations.RemoveField(
            model_name='caixa',
            name='evo_debito_apurado',
        ),
        migrations.RemoveField(
            model_name='caixa',
            name='evo_dinheiro_apurado',
        ),
        migrations.RemoveField(
            model_name='caixa',
            name='evo_pix_apurado',
        ),
        migrations.RemoveField(
            model_name='caixa',
            name='evo_total_apurado',
        ),
        migrations.AddField(
            model_name='caixa',
            name='anexo_filipeta',
            field=models.ImageField(blank=True, null=True, upload_to='filipetas/'),
        ),
        migrations.DeleteModel(
            name='AnexoCaixa',
        ),
    ]
