# Generated by Django 5.2.4 on 2025-08-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_caixa_evo_credito_apurado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracoes',
            fields=[
                ('id_fixo', models.IntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('unidade', models.CharField(default='Unidade Centro', max_length=100)),
                ('cnpj', models.CharField(default='12.345.678/0001-90', max_length=20)),
                ('endereco', models.CharField(default='Rua das Flores, 123', max_length=255)),
                ('telefone', models.CharField(default='(11) 99999-9999', max_length=20)),
                ('email', models.EmailField(default='contato@skyfit.com', max_length=254)),
                ('gympass', models.CharField(default='senha123', max_length=100, verbose_name='Senha Gympass')),
                ('radioSenha', models.CharField(default='senha456', max_length=100, verbose_name='Senha Rádio')),
                ('instagram', models.URLField(default='https://instagram.com/skyfit')),
            ],
            options={
                'verbose_name_plural': 'Configurações',
            },
        ),
    ]
